[TEST DNM] Build our very own ironic rpms and install them
openshift/ironic-image pull request #117
Opened 2020-11-10 18:19 UTC by elfosardo

2020-11-12 11:05 UTC, dtantsur requested changes
I've very much against maintaining a fork of the RPM spec (especially since we also need ironic-lib, ironic-python-agent and ironic-inspector). Can we maybe consider using DLRN, which is the RDO continuous delivery tool and is used in the TripleO CI for exactly the same purpose?

2020-11-13 07:29 UTC, elfosardo commented
/retest

2020-11-17 08:38 UTC, elfosardo commented
/retest

2021-01-13 19:56 UTC, iurygregory commented
/retest

seems like we need to update the Dockerfile ?

2021-01-14 09:19 UTC, elfosardo commented
@iurygregory thanks :)
I think I'm going to put this on hold for now, we've reached a similar goal in a different way

2021-02-04 17:18 UTC, elfosardo commented
this was nice
with the prevalidation jobs in place it's not needed anymore

2021-02-04 17:18 UTC, closed without merging