Bug 1915828: Latest Dell firmware (04.40.00.00) fails to install IPI on BM using idrac-virtualmedia protocol
openshift/ironic-image pull request #142
Opened 2021-01-25 14:35 UTC by iurygregory

This PR contains a fix in the sushy package [1] for the bz [2]

[1] https://github.com/openstack/sushy/commit/dfe6b33fa66072e9ead784d06fa30946ef922cb8
[2] https://bugzilla.redhat.com/show_bug.cgi?id=1915828

2021-01-25 14:38 UTC, iurygregory commented
/bugzilla refresh

2021-01-25 16:29 UTC, iurygregory commented
/hold

2021-01-25 16:37 UTC, iurygregory commented
/unhold

2021-01-25 16:37 UTC, iurygregory commented
/retest

2021-01-25 16:44 UTC, elfosardo commented
/test all

2021-01-25 16:56 UTC, elfosardo commented
/hold

2021-01-26 00:11 UTC, iurygregory commented
/test prevalidation-e2e-metal-ipi-virtualmedia-prevalidation

2021-01-26 02:36 UTC, iurygregory commented
/retest

2021-01-26 03:26 UTC, iurygregory commented
/retest

2021-01-26 07:15 UTC, elfosardo requested changes

2021-01-26 07:15 UTC, elfosardo commented on main-packages-list.txt
> +python3-sushy == 3.4.2-0.20210125195043.aeeb416.el8
please do not use '==', it's deprecated in favor of '=' and also we don't want to strictly pin a version but just provide a minimum working version

2021-01-26 15:20 UTC, iurygregory commented
/unhold

2021-01-26 19:56 UTC, elfosardo commented
/test all

2021-01-26 21:50 UTC, iurygregory commented
/retest

2021-01-26 22:20 UTC, iurygregory commented
Weird I see the `3.6` in the reposync 
`python-sushy-3.6.1-0.20210122201213.7ec0422.el8__noarch/ | 26-Jan-2021 16:46`

2021-01-26 22:21 UTC, iurygregory commented
/retest

2021-01-26 23:22 UTC, iurygregory commented
/retest

2021-01-26 23:45 UTC, iurygregory commented
/bugzilla refresh

2021-01-26 23:48 UTC, iurygregory commented
All green \o/

2021-01-27 08:28 UTC, elfosardo commented
/lgtm

2021-01-27 08:29 UTC, merged