Add ipxe support for arm64
openshift/ironic-image pull request #263
Opened 2022-04-01 19:58 UTC by jeffdyoung

2022-04-03 02:47 UTC, yselkowitz commented
The main-packages-list files need to be adjusted for the forthcoming packages names.

2022-04-08 17:48 UTC, yselkowitz commented
/test all

2022-04-08 22:04 UTC, yselkowitz commented
/test images

2022-04-09 13:17 UTC, jeffdyoung commented
/test images

2022-04-09 20:03 UTC, jeffdyoung commented
/test images

2022-04-10 01:41 UTC, yselkowitz commented
/test images

2022-04-10 19:13 UTC, yselkowitz commented
/test images

2022-04-10 19:47 UTC, yselkowitz commented
Filed https://bugzilla.redhat.com/show_bug.cgi?id=2073842 for the new mtools error; a workaround is:

```diff
--- a/prepare-efi.sh
+++ b/prepare-efi.sh
@@ -23,1 +23,1 @@ else
-dnf install -y grub2 shim dosfstools mtools $PACKAGES
+dnf install -y glibc-gconv-extra grub2 shim dosfstools mtools $PACKAGES
```

2022-04-11 06:49 UTC, elfosardo commented
> Filed https://bugzilla.redhat.com/show_bug.cgi?id=2073842 for the new mtools error; a workaround is:
> 
> ```diff
> --- a/prepare-efi.sh
> +++ b/prepare-efi.sh
> @@ -23,1 +23,1 @@ else
> -dnf install -y grub2 shim dosfstools mtools $PACKAGES
> +dnf install -y grub2 shim dosfstools mtools glibc-gconv-extra $PACKAGES
> ```

@yaacov thanks for opening the BZ, this has been already worked around upstream https://github.com/metal3-io/ironic-image/blob/main/Dockerfile#L9
I'm going to move the glibc-gconv-extra to prepare-efi.sh so we don't diverge too much

2022-04-15 13:40 UTC, elfosardo commented
/hold
this should wait for https://github.com/openshift/ironic-image/pull/267

2022-04-20 17:12 UTC, yselkowitz commented
/test all

2022-04-21 07:43 UTC, elfosardo commented
/retest

2022-04-21 14:21 UTC, elfosardo commented
/test prevalidation-e2e-metal-ipi-prevalidation

2022-04-22 14:24 UTC, jeffdyoung commented
/retest

2022-04-22 20:46 UTC, elfosardo requested changes
the errors seem related to this change, please check my comments

2022-04-22 20:46 UTC, elfosardo commented on ironic-config/dnsmasq.conf.j2
> +dhcp-match=set:efi,option:client-arch,11
let's move this back to L26 but change the set to efi_arm64

2022-04-22 20:46 UTC, elfosardo commented on ironic-config/dnsmasq.conf.j2
> +dhcp-boot=tag:efi,tag:!ipxe,/arm64-efi/snponly.efi
let's set the tag here to efi_arm64

2022-04-28 19:12 UTC, yselkowitz commented
How do we need to handle upstreaming this to metal3 so that these changes don't get lost at the next sync?  The upstream Dockerfile builds ipxe from a git checkout which is newer than the C9S RPM packages, but that doesn't really give a way to build both x86 and arm simultaneously.  Does that mean the additions to `scripts/rundnsmasq` need to be made conditional?  (prepare-ipxe.sh is downstream-specific so no changes needed there.)  Are the changes to dnsmasq.conf.j2 safe even if the arm64 efi files are absent upstream?

2022-04-29 03:12 UTC, yselkowitz commented
/assign @elfosardo

2022-04-29 14:57 UTC, elfosardo commented
> How do we need to handle upstreaming this to metal3 so that these changes don't get lost at the next sync? The upstream Dockerfile builds ipxe from a git checkout which is newer than the C9S RPM packages, but that doesn't really give a way to build both x86 and arm simultaneously. Does that mean the additions to `scripts/rundnsmasq` need to be made conditional? (prepare-ipxe.sh is downstream-specific so no changes needed there.) Are the changes to dnsmasq.conf.j2 safe even if the arm64 efi files are absent upstream?

the upstream-downstream sync is done manually so we preserve what's needed for downstream
I don't think we need to make the changes conditional, but I guess proposing the change upstream and see how the CI reacts would be a good test

2022-04-29 14:57 UTC, elfosardo approved these changes

2022-04-29 14:58 UTC, yselkowitz commented
/hold cancel
/lgtm

2022-04-29 15:01 UTC, merged