Bug 2048672: Enable vMedia provisioning of Nokia servers
openshift/ironic-image pull request #275
Opened 2022-05-12 13:05 UTC by rhjanders

This commit brings the upstream OpenStack/Sushy fixes required
for virtual media based provisioning of Nokia servers into
OpenShift:

https://review.opendev.org/c/openstack/sushy/+/840653
https://review.opendev.org/c/openstack/sushy/+/840654
https://review.opendev.org/c/openstack/sushy/+/840655

2022-05-12 13:08 UTC, rhjanders commented
/bugzilla refresh

2022-05-12 14:02 UTC, elfosardo requested changes

2022-05-12 14:02 UTC, elfosardo commented on main-packages-list.txt
> +python3-sushy >= python-sushy-3.7.4-0.20220512110955.e0d5bde.el8
should just be the version

2022-05-12 14:20 UTC, elfosardo commented
/hold
need to fix the version

2022-05-13 00:51 UTC, iurygregory commented
/hold cancel

2022-05-13 03:24 UTC, rhjanders commented
/test prevalidation-e2e-metal-ipi-virtualmedia-prevalidation

2022-05-13 05:08 UTC, rhjanders commented
/test prevalidation-e2e-metal-ipi-prevalidation

2022-05-13 07:33 UTC, elfosardo approved these changes

2022-05-13 07:33 UTC, elfosardo commented
/retest

2022-05-13 08:36 UTC, elfosardo commented
/bugzilla refresh

2022-05-13 11:00 UTC, rhjanders commented
/test images

2022-05-13 11:11 UTC, dtantsur commented
/lgtm

Ready to go when the CI passes and the dependent bug is verified.

2022-05-13 12:05 UTC, elfosardo commented
/test images

2022-05-13 12:09 UTC, elfosardo commented
/test images
ci-operator uber fail

2022-05-13 12:15 UTC, elfosardo commented
/unhold

2022-05-13 12:17 UTC, elfosardo commented
/bugzilla refresh

2022-05-16 12:21 UTC, lshilin-r commented
/label cherry-pick-approved

2022-05-16 12:23 UTC, merged