autodetect efi directory
openshift/ironic-image pull request #496
Opened 2024-05-06 14:59 UTC by karmab

2024-05-06 15:30 UTC, LorbusChris commented on prepare-efi.sh
>  DEST=${2:-/tmp/esp.img}
This would become the new first arg

2024-05-06 15:52 UTC, LorbusChris commented on Dockerfile.fcos
> -RUN prepare-efi.sh fedora
Dockerfile.scos needs the analogue change

2024-05-06 18:31 UTC, LorbusChris approved these changes

2024-05-06 18:31 UTC, LorbusChris commented
/lgtm

2024-06-10 09:18 UTC, elfosardo requested changes
was this tested? does this need to be changed also upstream in metal3?

2024-06-10 13:07 UTC, closed without merging