Sync with upstream metal3-io/ironic-image
openshift/ironic-image pull request #532
Opened 2024-07-23 11:17 UTC by MahnoorAsghar

2024-07-23 12:09 UTC, MahnoorAsghar commented
I tried to get rid of the Makefile change, with little success ^

2024-07-23 12:58 UTC, elfosardo commented
/hold
some more changes are needed if you're removing inspector
check requirements.cachito and prepare-image.sh

2024-07-23 15:47 UTC, elfosardo commented
/approve
change looks good
let's see what the CI says
thanks!

2024-07-23 15:48 UTC, elfosardo commented
/unhold

2024-07-23 15:48 UTC, elfosardo commented
/cc @dtantsur

2024-07-23 16:16 UTC, dtantsur requested changes

2024-07-23 16:24 UTC, MahnoorAsghar commented on prepare-image.sh
> -    INSPECTOR_GID=1004
CBO does not specify the UIDs and GIDs anymore

2024-07-23 16:26 UTC, MahnoorAsghar commented on ironic-config/ironic.conf.j2
> -extra_kernel_params = ipa-inspection-collectors={{ env.IRONIC_IPA_COLLECTORS }} ipa-enable-vlan-interfaces={{ env.IRONIC_ENABLE_VLAN_INTERFACES }} ipa-inspection-dhcp-all-interfaces=1 ipa-collect-lld
My bad, I thought this was tied to inspector alone.

2024-07-23 16:27 UTC, MahnoorAsghar commented on ironic-config/ironic.conf.j2
> -keep_ports = present
Lines 150-155 need to be removed, and 156-164 need to be kept?

2024-07-23 16:52 UTC, MahnoorAsghar commented on ironic-config/ironic.conf.j2
> -keep_ports = present
Edited to remove the if block 

> if env.USE_IRONIC_INSPECTOR == "true"

2024-07-23 16:52 UTC, MahnoorAsghar commented on prepare-image.sh
> -    INSPECTOR_GID=1004
They were only being specified for the inspector container in CBO, which is now removed

2024-07-24 10:56 UTC, dtantsur approved these changes

2024-07-24 10:57 UTC, dtantsur commented
/lgtm

2024-07-24 11:01 UTC, merged